name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt
        
  download:  # New Job: Download
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after 'build' job

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: ./artifacts  # Download to ./artifacts directory

      - name: Display file content
        run: cat ./artifacts/hello.txt  # Print file content
